services:
  feihai-drive:
    build: .
    image: feihai-drive:1.0.24
    container_name: feihai-drive
    restart: unless-stopped
    ports:
      - "12366:12366"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
